# Dependencies
markdown:            kramdown
highlighter:         pygments

# Gems
gems: [jekyll-paginate]

# Permalinks
permalink:           pretty

# Setup
title:               Musings on R and C++
tagline:             ''
description:         ''
home:                http://kevinushey.github.io
url:                 http://kevinushey.github.io/blog
baseurl:             /blog
paginate:            5
paginate_path:       "page:num"
exclude:             ['posts']

# About/contact
author:
  name:              Kevin Ushey
  url:               https://twitter.com/kevin_ushey
  email:             kevinushey@gmail.com

# Custom vars
version:             1.0.0

