# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               ''
tagline:             ''
description:         ''
home:                http://kevinushey.github.io
url:                 http://kevinushey.github.io/blog
baseurl:             /blog
paginate:            5
paginate_path:       "/page:num/"
exclude:             ['posts']

# About/contact
author:
  name:              Kevin Ushey
  url:               https://twitter.com/kevin_ushey
  email:             kevinushey@gmail.com

# Custom vars
version:             1.0.0
